**1. Setting Up and Loading Data**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

/kaggle/input/datasets/usamaumair/food-delivery-orders-dataset-2023/food_delivery_orders.csv

In [2]:
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams["figure.figsize"] = (10,5)

df = pd.read_csv("/kaggle/input/datasets/usamaumair/food-delivery-orders-dataset-2023/food_delivery_orders.csv", parse_dates=["order_date"])
print(df.shape)
df.head()

(43141, 18)

,order_id,order_date,time_slot,restaurant_id,restaurant_name,cuisine_type,city,order_value,discount_amount,tip_amount,delivery_time_minutes,is_late_delivery,rating,customer_type,payment_method,promo_used,is_weekend,is_holiday
0,528425,2023-08-26,Dinner (6-9pm),R0028,Burgers House 28,Burgers,Chicago,11.42,2.28,2.28,35.5,False,3.5,New,Digital Wallet,True,True,False
1,535327,2023-10-27,Lunch (12-2pm),R0056,Salads House 56,Salads & Healthy,Seattle,15.09,1.51,2.26,26.8,False,3.5,New,Digital Wallet,True,False,False
2,509874,2023-03-27,Dinner (6-9pm),R0105,Burgers House 105,Burgers,Denver,12.94,0.00,3.24,34.0,False,4.0,Returning,Digital Wallet,False,False,False
3,533145,2023-10-07,Dinner (6-9pm),R0120,Pizza House 120,Pizza,Miami,19.03,0.00,2.85,36.8,False,3.5,Returning,Digital Wallet,False,True,False
4,539600,2023-12-02,Dinner (6-9pm),R0047,Burgers House 47,Burgers,Seattle,20.52,0.00,5.13,35.3,False,4.5,New,Digital Wallet,False,True,False

**2. First Look**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43141 entries, 0 to 43140
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               43141 non-null  int64
 1   order_date             43141 non-null  datetime64[ns]
 2   time_slot              43141 non-null  object
 3   restaurant_id          43141 non-null  object
 4   restaurant_name        43141 non-null  object
 5   cuisine_type           43141 non-null  object
 6   city                   43141 non-null  object
 7   order_value            43141 non-null  float64
 8   discount_amount        43141 non-null  float64
 9   tip_amount             43141 non-null  float64
 10  delivery_time_minutes  43141 non-null  float64
 11  is_late_delivery       43141 non-null  bool
 12  rating                 42278 non-null  float64
 13  customer_type          42795 non-null  object
 14  payment_method         42623 non-null  object
 15  promo_used             43141 non-null  bool
 16  is_weekend             43141 non-null  bool
 17  is_holiday             43141 non-null  bool
dtypes: bool(4), datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 4.8+ MB

In [4]:
df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
order_id,43141.0,NaN,NaN,NaN,521533.361837,500001.0,510767.0,521532.0,532302.0,543063.0,12431.687156
order_date,43141,NaN,NaN,NaN,2023-07-01 13:18:09.404510720,2023-01-01 00:00:00,2023-04-04 00:00:00,2023-06-30 00:00:00,2023-09-30 00:00:00,2023-12-31 00:00:00,NaN
time_slot,43141,5,Dinner (6-9pm),18225,NaN,NaN,NaN,NaN,NaN,NaN,NaN
restaurant_id,43141,159,R0048,573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
restaurant_name,43141,159,Burgers House 48,573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cuisine_type,43141,8,Burgers,8859,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,43141,8,Minneapolis,5966,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_value,43141.0,NaN,NaN,NaN,20.710146,5.0,14.41,19.34,25.2,54.98,8.679149
discount_amount,43141.0,NaN,NaN,NaN,0.486877,0.0,0.0,0.0,0.0,10.98,1.291281
tip_amount,43141.0,NaN,NaN,NaN,3.169333,0.0,1.94,2.96,4.23,13.72,1.967385
delivery_time_minutes,43141.0,NaN,NaN,NaN,34.348047,10.6,27.0,33.1,40.1,392.4,11.250898
is_late_delivery,43141,2,False,37358,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rating,42278.0,NaN,NaN,NaN,4.038815,2.0,3.5,4.0,4.5,5.0,0.582672
customer_type,42795,3,Returning,21472,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_method,42623,4,Credit Card,17205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_used,43141,2,False,36373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_weekend,43141,2,False,27854,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_holiday,43141,2,False,41492,NaN,NaN,NaN,NaN,NaN,NaN,NaN